"""Add first_name and last_name to users table

Revision ID: a04322642355
Revises: 1edb4ba836b5
Create Date: 2025-05-08 11:25:35.989896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a04322642355'
down_revision: Union[str, None] = '1edb4ba836b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First drop the foreign key constraint in the items table
    # This must happen before dropping the item_categories table
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('items_category_id_fkey', type_='foreignkey')
    
    # Now we can safely drop the item_categories table
    op.drop_table('item_categories')
    
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('resource_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.String(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('details',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_branches_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_branches_name'), ['name'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('id_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('id_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('id_expiry', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('credit_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_customers_customer_code'), ['customer_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_id'), ['id'], unique=False)

    with op.batch_alter_table('employee_types', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_employee_types_id'), ['id'], unique=False)
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('branch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('employee_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('hire_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_employees_id'), ['id'], unique=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.Enum('JEWELRY', 'ELECTRONICS', 'MUSICAL_INSTRUMENTS', 'TOOLS', 'WATCHES', 'FIREARMS', 'COLLECTIBLES', 'LUXURY_ITEMS', 'OTHER', name='itemcategory'), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('condition', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('serial_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('appraised_value', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('loan_value', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('acquisition_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('redemption_deadline', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('sold_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('storage_location', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('images', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('appraised_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('application_id', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('AVAILABLE', 'PAWNED', 'SOLD', 'EXPIRED', name='itemstatus'),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_item_code'), ['item_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_items_name'), ['name'], unique=False)
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'])
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'])
        batch_op.create_foreign_key(None, 'employees', ['appraised_by_id'], ['id'])
        batch_op.drop_column('appraisal_value')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('application_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('principal_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('extended_due_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('actual_end_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('total_paid', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('remaining_balance', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('extension_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('interest_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('term_days',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_loans_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loans_loan_number'), ['loan_number'], unique=True)
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'])
        batch_op.drop_column('end_date')
        batch_op.drop_column('amount')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('reference_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('loan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('payment_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_payments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_payment_number'), ['payment_number'], unique=True)
        batch_op.drop_constraint('payments_transaction_id_fkey', type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('transaction_id')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
        batch_op.drop_constraint('permissions_name_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_permissions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_name'), ['name'], unique=True)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
        batch_op.drop_constraint('roles_name_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_roles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('processed_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('transaction_type', sa.Enum('PAWN', 'REDEMPTION', 'SALE', 'PAYMENT', 'EXTENSION', 'REFUND', 'ADJUSTMENT', name='transactiontype'), nullable=True))
        batch_op.add_column(sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_number'), ['transaction_number'], unique=True)
        batch_op.drop_constraint('transactions_loan_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'])
        batch_op.create_foreign_key(None, 'payments', ['payment_id'], ['id'])
        batch_op.create_foreign_key(None, 'employees', ['processed_by_id'], ['id'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('loan_id')
        batch_op.drop_column('type')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_superuser', sa.Boolean(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
        batch_op.drop_constraint('users_email_key', type_='unique')
        batch_op.drop_constraint('users_username_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint('users_username_key', ['username'])
        batch_op.create_unique_constraint('users_email_key', ['email'])
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('is_superuser')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', postgresql.ENUM('LOAN', 'PAYMENT', 'RENEWAL', 'REDEMPTION', 'SALE', name='transactiontype'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('loan_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transactions_loan_id_fkey', 'loans', ['loan_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_number'))
        batch_op.drop_index(batch_op.f('ix_transactions_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.drop_column('notes')
        batch_op.drop_column('transaction_date')
        batch_op.drop_column('transaction_type')
        batch_op.drop_column('payment_id')
        batch_op.drop_column('processed_by_id')
        batch_op.drop_column('customer_id')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('transaction_number')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.drop_index(batch_op.f('ix_roles_id'))
        batch_op.create_unique_constraint('roles_name_key', ['name'])
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.alter_column('permission_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_name'))
        batch_op.drop_index(batch_op.f('ix_permissions_id'))
        batch_op.create_unique_constraint('permissions_name_key', ['name'])
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('payments_transaction_id_fkey', 'transactions', ['transaction_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_payments_payment_number'))
        batch_op.drop_index(batch_op.f('ix_payments_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('payment_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('loan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('notes')
        batch_op.drop_column('reference_number')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('payment_number')

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_loans_loan_number'))
        batch_op.drop_index(batch_op.f('ix_loans_id'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               nullable=False)
        batch_op.alter_column('term_days',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('interest_rate',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('notes')
        batch_op.drop_column('extension_count')
        batch_op.drop_column('remaining_balance')
        batch_op.drop_column('total_paid')
        batch_op.drop_column('actual_end_date')
        batch_op.drop_column('extended_due_date')
        batch_op.drop_column('due_date')
        batch_op.drop_column('principal_amount')
        batch_op.drop_column('application_id')
        batch_op.drop_column('loan_number')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('appraisal_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('items_category_id_fkey', 'item_categories', ['category_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_items_name'))
        batch_op.drop_index(batch_op.f('ix_items_item_code'))
        batch_op.drop_index(batch_op.f('ix_items_id'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('AVAILABLE', 'PAWNED', 'SOLD', 'EXPIRED', name='itemstatus'),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('application_id')
        batch_op.drop_column('appraised_by_id')
        batch_op.drop_column('images')
        batch_op.drop_column('storage_location')
        batch_op.drop_column('notes')
        batch_op.drop_column('sold_date')
        batch_op.drop_column('redemption_deadline')
        batch_op.drop_column('acquisition_date')
        batch_op.drop_column('sale_price')
        batch_op.drop_column('loan_value')
        batch_op.drop_column('appraised_value')
        batch_op.drop_column('serial_number')
        batch_op.drop_column('condition')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('category')
        batch_op.drop_column('item_code')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_id'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('hire_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               nullable=False)
        batch_op.alter_column('employee_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('branch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('employee_types', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_employee_types_id'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_id'))
        batch_op.drop_index(batch_op.f('ix_customers_email'))
        batch_op.drop_index(batch_op.f('ix_customers_customer_code'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('notes')
        batch_op.drop_column('credit_score')
        batch_op.drop_column('is_active')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('id_expiry')
        batch_op.drop_column('id_number')
        batch_op.drop_column('id_type')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('country')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('customer_code')

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branches_name'))
        batch_op.drop_index(batch_op.f('ix_branches_id'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.alter_column('details',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('user_agent')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('resource_id')
        batch_op.drop_column('resource_type')

    op.create_table('item_categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='item_categories_pkey')
    )
    # ### end Alembic commands ###
