"""Add first_name and last_name to users table

Revision ID: a26726d1b6fb
Revises: a04322642355
Create Date: 2025-05-08 11:37:39.018518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a26726d1b6fb'
down_revision: Union[str, None] = 'a04322642355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        # Drop primary key constraint first
        batch_op.drop_constraint('role_permissions_pkey', type_='primary')
        
        # Allow NULLs on both columns
        batch_op.alter_column('role_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        batch_op.alter_column('permission_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        
        # Recreate primary key without these columns if needed

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.alter_column('permission_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
